import { BottleData } from './types';

// Aura-Soma Realistic Color Palette
const C = {
  RoyalBlue: { hex: "#1f2db2", label: "Royal Blue" },
  MidToneRoyalBlue: { hex: "#3457D5", label: "Mid Tone Royal Blue" },
  Blue: { hex: "#005ce5", label: "Blue" },
  PaleBlue: { hex: "#A6D4FF", label: "Pale Blue" },
  Turquoise: { hex: "#00C2CB", label: "Turquoise" },
  MidToneTurquoise: { hex: "#48D1CC", label: "Mid Tone Turquoise" },
  PaleTurquoise: { hex: "#AFEEEE", label: "Pale Turquoise" },
  OpalescentTurquoise: { hex: "#E0FFFF", label: "Opalescent Turquoise" },
  Green: { hex: "#009944", label: "Green" },
  EmeraldGreen: { hex: "#008f39", label: "Emerald" },
  LimeGreen: { hex: "#caf01a", label: "Lime Green" },
  PaleGreen: { hex: "#98FB98", label: "Pale Green" },
  Olive: { hex: "#808000", label: "Olive" },
  DeepOlive: { hex: "#3B4518", label: "Deep Olive" },
  MidToneOlive: { hex: "#d5e276", label: "Mid Tone Olive" },
  PaleOlive: { hex: "#9ACD32", label: "Pale Olive" },
  Yellow: { hex: "#FFF200", label: "Yellow" },
  PaleYellow: { hex: "#FFFFE0", label: "Pale Yellow" },
  LemonYellow: { hex: "#fef75f", label: "Lemon Yellow" },
  LemonChiffon: { hex: "#FFFACD", label: "Lemon Chiffon" },
  Gold: { hex: "#ffb82c", label: "Gold" },
  Orange: { hex: "#FF7500", label: "Orange" },
  PaleOrange: { hex: "#FFDAB9", label: "Pale Orange" },
  Coral: { hex: "#e34925", label: "Coral" },
  MidToneCoral: { hex: "#f05a42", label: "Mid Tone Coral" },
  PaleCoral: { hex: "#f49570", label: "Pale Coral" }, 
  Red: { hex: "#E60012", label: "Red" },
  Pink: { hex: "#ffa2b1", label: "Pink" },
  PalePink: { hex: "#FFB6C1", label: "Pale Pink" },
  RosePink: { hex: "#ff86aa", label: "Rose Pink" },
  PaleRosePink: { hex: "#FF66CC", label: "Pale Rose Pink" },
  Magenta: { hex: "#E20074", label: "Magenta" },
  BrightMagenta: { hex: "#FF0090", label: "Bright Magenta" },
  DeepMagenta: { hex: "#63004F", label: "Deep Magenta" },
  Violet: { hex: "#7F00FF", label: "Violet" },
  Purple: { hex: "#6A0DAD", label: "Purple" },
  PaleViolet: { hex: "#D8BFD8", label: "Pale Violet" },
  Lilac: { hex: "#DA70D6", label: "Lilac" },
  Clear: { hex: "#FFFFFF", label: "Clear" },
  White: { hex: "#FFFFFF", label: "White" },
  Black: { hex: "#000000", label: "Black" }, 
};

// Helper to create bottle quickly with optional details
const createBottle = (
  num: number, 
  name: string, 
  top: {hex: string, label: string}, 
  bottom: {hex: string, label: string}, 
  theme: string, 
  affirmation: string, 
  tags: string[] = [],
  details: Partial<Omit<BottleData, 'id' | 'number' | 'name' | 'colors' | 'theme' | 'affirmation' | 'tags'>> = {}
): BottleData => ({
  id: num.toString(),
  number: num,
  name,
  colors: { top: top.hex, bottom: bottom.hex, topLabel: top.label, bottomLabel: bottom.label },
  theme,
  affirmation,
  tags,
  // Automatically assign tarot image path assuming they are in public/tarot folder
  // Removed leading slash to make it relative path (better for sub-directory hosting)
  tarotImage: `tarot/${num}.jpg`,
  ...details
});

export const BOTTLES: BottleData[] = [
  createBottle(0, "靈性解救", C.RoyalBlue, C.DeepMagenta, "接受完整的自己，獲得深層的洞見與平靜。", "我愛原本的我，生命全然地支持著我。", ["Rescue"], {
    alias: "Equilibrium_0 靈性解救",
    mixedColor: "深紫紅色",
    tarot: "愚者",
    positivePersonality: "這是一個擁有極大直覺力的人，同時具有治療他人的潛能。能夠幫助別人找到他們的人生目標。對於問題具有深層的洞見。",
    challengePersonality: "對於自己的感官或直覺過於敏感，容易因為他人的能量而感到疲憊。可能還沒準備好要完全落實在這個物質世界。",
    spiritualLevel: "幫助靈魂深處的轉化，帶來靈性的清晰度。有助於連結更高的意識。",
    mentalLevel: "平靜過度活躍的心智，帶來深層的寧靜。",
    emotionalLevel: "安撫深層的情緒困擾，尤其是那些無法用言語表達的感受。",
    physicalLevel: "對於頭痛、失眠或感官過度敏感有幫助。",
    whereToApply: "沿著頭髮邊緣、太陽穴、頸部，以及腳底。"
  }),

  createBottle(1, "身體解救", C.Blue, C.DeepMagenta, "治療者的瓶子，完整的溝通與平和。", "我是完整的，我療癒我自己。", ["Rescue"], {
    alias: "Equilibrium_1 身體解救",
    mixedColor: "深紫紅色",
    tarot: "魔術師",
    positivePersonality: "一個能夠幫助他人療癒的人，不僅是身體上的，也包括心理上的。具有很強的溝通能力，能夠將複雜的事情簡單化。",
    challengePersonality: "可能傾向於過度付出，忘記照顧自己的需求。容易在幫助別人的過程中耗盡自己的能量。",
    spiritualLevel: "幫助整合身心靈，讓靈性的洞見能夠落實在日常生活中。",
    mentalLevel: "有助於集中注意力，清晰地表達自己的想法。",
    emotionalLevel: "平撫情緒的波動，帶來內在的和平。",
    physicalLevel: "對於喉嚨痛、頸部僵硬、甲狀腺問題有舒緩作用。也適用於各種急救狀況。",
    whereToApply: "沿著頭髮邊緣、頸部周圍，以及受傷或疼痛的部位。"
  }),
  
  createBottle(2, "和平瓶", C.Blue, C.Blue, "通過我們，而非經由我們所傳遞的和平溝通管道，滋養的能量。", "我吸進和平，我呼出和平。", ["Chakra"], {
    alias: "Equilibrium_2 2-和平~女祭司(向外)",
    mixedColor: "藍色",
    tarot: "女祭司",
    positivePersonality: "喜愛和平，跟自己很和諧地相處。承諾要追求和平。善用與喉輪有關的創造力(譬如跟演說有關)。支持別人。不管此人是男人或女人，都具有很強的女性品質，或跟夏娃和埃及女神的類型有很親密的連結。能夠成為一個來自其它層面訊息的通道。",
    challengePersonality: "很難找到內在和外在的和平，一方面在男性能量部份有問題；另一方面非常缺乏滋潤的能量(既不能接受它，也不能給出它)。害怕未知。",
    spiritualLevel: "幫助取得跟一個人內在較深層面的連繫，同時有能力變成一個通道，那個意思就是說讓來自其它層面的資訊通過。可淨化個人氛圍。可以使垂死時的轉化變得容易些。可以幫助那些隨著月相會產生心情擺盪的人。幫助進入很深的直覺。",
    mentalLevel: "撫慰害怕恐懼未知的人，也有助於與專心和說話有關的困難。幫助發展創造力和直覺力。",
    emotionalLevel: "使過渡轉變期變得更容易，比如在垂死的時候、女人在生產時、或是處於危機狀態下。使你能夠進入寧靜的力量；在充滿情緒的情況之中或之後可以幫助你平衡；可以使你覺得被保護。幫助你解夢。",
    physicalLevel: "用這一瓶對甲狀腺亢奮或活力不足有幫助。對內分泌系統的問題、表達的障礙、感染和瘀傷等有幫助，同時對分娩及幼兒長牙齒有幫助。",
    whereToApply: "全身皆可使用，可特別沿著頭髮邊緣、脖子上下顎與頸部之間，抹在整個喉嚨和頸部。"
  }),

  createBottle(3, "心輪瓶 / 亞特蘭提斯", C.Blue, C.Green, "心的表達與創造力，連結亞特蘭提斯的智慧。", "我表達我的心，我分享我的愛。", ["Heart"], {
    alias: "Equilibrium_3 心輪瓶",
    mixedColor: "綠松石色",
    tarot: "皇后",
    positivePersonality: "一個具有創造力與溝通能力的人。能夠真誠地表達內心的感受。與大自然和動物有很深的連結。具有藝術天分。",
    challengePersonality: "可能在表達情感上有困難，容易因為害怕受傷而封閉自己的心。對於空間（不管是物理空間還是心理空間）有強烈的需求。",
    spiritualLevel: "幫助打開心輪，連結更高的愛與智慧。喚醒關於亞特蘭提斯古老智慧的記憶。",
    mentalLevel: "激發想像力與創造性思維。有助於看到事情的整體畫面。",
    emotionalLevel: "療癒心輪的創傷，釋放嫉妒與羨慕的情緒。帶來情感上的自由。",
    physicalLevel: "對胸腔、心臟、肺部以及免疫系統有益。",
    whereToApply: "整個胸部區域，從鎖骨到肋骨下方。"
  }),

  createBottle(4, "太陽瓶", C.Yellow, C.Gold, "內在的知識與智慧，太陽神經叢的開啟。", "我是安全的，我擁有內在的智慧。", ["Wisdom"], {
    alias: "Equilibrium_4 太陽瓶",
    mixedColor: "金黃色",
    tarot: "皇帝",
    positivePersonality: "一個充滿快樂、幽默感與智慧的人。擁有強大的組織能力與邏輯思考能力。清楚自己的價值，並能將知識轉化為智慧。",
    challengePersonality: "可能過於理性，忽略了感受。容易焦慮、緊張，或對未來感到恐懼。有控制欲。",
    spiritualLevel: "連結內在的陽光，帶來開悟與覺醒。幫助區分知識（來自外在）與智慧（來自內在）。",
    mentalLevel: "增強學習能力，幫助吸收與消化資訊。",
    emotionalLevel: "釋放深層的恐懼與焦慮，帶來歡笑與喜悅。",
    physicalLevel: "對消化系統、胃、肝臟、膽囊有幫助。有助於平衡新陳代謝。",
    whereToApply: "太陽神經叢（肚臍上方與肋骨之間）區域。"
  }),

  createBottle(5, "日出 / 日落", C.Yellow, C.Red, "釋放儲存的能量，重新覺醒生命的熱情。", "我敞開自己，迎接生命中的喜悅。", ["Energy"], {
    alias: "Equilibrium_5 日出 / 日落",
    mixedColor: "橘色",
    tarot: "教皇",
    positivePersonality: "充滿活力與能量的人，能夠將想法付諸行動。具有領導特質，能夠激勵他人。擁有生活智慧。",
    challengePersonality: "可能在性的能量上有壓抑或困擾。容易感到疲憊，缺乏生活的動力。可能有生存恐懼。",
    spiritualLevel: "喚醒昆達里尼能量，幫助靈性落實。帶來對生命的熱愛與感激。",
    mentalLevel: "幫助解決關於生存議題的困惑。",
    emotionalLevel: "釋放壓抑的憤怒與挫折感，轉化為建設性的力量。",
    physicalLevel: "對生殖系統、下背部痛、疲勞有幫助。",
    whereToApply: "整個下腹部周圍。"
  }),

  createBottle(6, "能量瓶", C.Red, C.Red, "落實與行動，無條件的愛與熱情。", "大地支持著我，我充滿活力。", ["Energy", "Root"], {
    alias: "Equilibrium_6 能量瓶",
    mixedColor: "紅色",
    tarot: "戀人",
    positivePersonality: "一個非常腳踏實地、勇敢且充滿熱情的人。擁有強大的行動力與生存意志。願意為愛付出。",
    challengePersonality: "可能容易憤怒、急躁或具有侵略性。在物質層面有過度的執著或不安全感。",
    spiritualLevel: "幫助靈魂完全進入身體，扎根於大地。帶來無私的愛與犧牲的精神。",
    mentalLevel: "增強意志力與決心。",
    emotionalLevel: "處理憤怒、怨恨與受傷的感覺。幫助在關係中設立健康的界線。",
    physicalLevel: "對血液循環、肌肉、海底輪相關問題有幫助。增加體力。",
    whereToApply: "臀部、雙腿、腳底。"
  }),

  createBottle(7, "客西馬尼花園", C.Yellow, C.Green, "最後的信心考驗，信任生命的過程。", "我信任生命之流，一切都是最好的安排。", ["Test"], {
    alias: "Equilibrium_7 客西馬尼花園",
    mixedColor: "橄欖綠",
    tarot: "戰車",
    positivePersonality: "一個在困難中仍能保持信任與希望的人。具有開拓者的精神。能夠在混亂中找到方向。",
    challengePersonality: "容易陷入嫉妒、羨慕或懷疑的情緒。可能面臨信仰的考驗，覺得被遺棄。",
    spiritualLevel: "幫助在最黑暗的時刻保持信心。測試與考驗是為了帶來更大的成長。",
    mentalLevel: "幫助做出正確的決定，不再猶豫不決。",
    emotionalLevel: "釋放苦澀與怨恨，帶來心靈的空間與自由。",
    physicalLevel: "對免疫系統、胸部與心臟區域有益。",
    whereToApply: "心輪與太陽神經叢之間的區域。"
  }),

  createBottle(8, "阿努比斯", C.Yellow, C.Blue, "衡量心靈的輕盈，釋放批判與罪惡感。", "我的心輕如羽毛，我活在當下。", ["Egyptian"], {
    alias: "Equilibrium_8 阿努比斯",
    mixedColor: "綠色",
    tarot: "正義",
    positivePersonality: "一個具有平衡感、邏輯清晰且富有正義感的人。能夠客觀地看待事物，不帶批判。",
    challengePersonality: "傾向於過度思考，容易批判自己與他人。可能有深層的罪惡感或恐懼。",
    spiritualLevel: "幫助衡量心的輕盈，釋放業力的負擔。提醒我們活在當下。",
    mentalLevel: "平衡理性與感性，帶來清晰的判斷力。",
    emotionalLevel: "釋放罪惡感、恐懼與焦慮。帶來內在的平靜。",
    physicalLevel: "對肝臟、神經系統與消化系統有幫助。",
    whereToApply: "整個軀幹。"
  }),

  createBottle(9, "水晶洞 / 心中之心", C.Turquoise, C.Green, "在獨處中發現真理，展開個體化的旅程。", "我在內在的寂靜中聽見真理。", ["Heart"], {
    alias: "Equilibrium_9 水晶洞",
    mixedColor: "綠松石色",
    tarot: "隱士",
    positivePersonality: "一個追求真理、喜歡獨處並具有人道主義精神的人。透過內在的探索來服務世界。",
    challengePersonality: "可能感到孤獨或與世隔絕。容易陷入過度理想化或逃避現實。",
    spiritualLevel: "幫助進入內在的寂靜，傾聽內在導師的聲音。個體化過程的開始。",
    mentalLevel: "激發創造性溝通與哲學思考。",
    emotionalLevel: "幫助表達深層的情感，釋放壓抑的淚水。",
    physicalLevel: "對心臟、肺部、胸腺與免疫系統有益。",
    whereToApply: "整個胸部區域。"
  }),

  createBottle(10, "去擁抱一棵樹", C.Green, C.Green, "給予自己空間，做出明智的決定。", "我有足夠的空間去成長與呼吸。", ["Karma"], {
    alias: "Equilibrium_10 去擁抱一棵樹",
    mixedColor: "綠色",
    tarot: "命運之輪",
    positivePersonality: "一個能夠給予他人空間與支持的人。具有良好的決策能力與領導力。與自然和諧共處。",
    challengePersonality: "可能被嫉妒、羨慕的感覺困擾。難以做出決定，覺得被困住。",
    spiritualLevel: "幫助種下善的種子（業力）。連結大自然的智慧與力量。",
    mentalLevel: "帶來清晰的視野與方向感。",
    emotionalLevel: "釋放情感上的糾結與執著，帶來自由。",
    physicalLevel: "對心臟、肺部與呼吸系統有幫助。舒緩胸悶。",
    whereToApply: "整個胸部區域。"
  }),

  createBottle(11, "一串花朵 / 愛的精髓", C.Clear, C.Pink, "無條件的愛之鍊，接納原本的自己。", "我愛原本的自己，正如我愛他人一樣。", ["Love"], {
    alias: "Equilibrium_11 一串花朵",
    mixedColor: "淡粉紅色",
    tarot: "力量",
    positivePersonality: "一個充滿愛心、溫柔且具有同理心的人。能夠無條件地接納自己與他人。看到事物美好的一面。",
    challengePersonality: "可能過度依賴他人的愛與認同。容易感到受傷或被拒絕。難以愛自己。",
    spiritualLevel: "帶來基督意識的愛（無條件的愛）。幫助靈性重生。",
    mentalLevel: "消除對愛的扭曲觀念，建立健康的自我價值。",
    emotionalLevel: "療癒缺乏愛的創傷，尤其是童年時期的。帶來溫暖與滋養。",
    physicalLevel: "對生殖系統、荷爾蒙平衡、皮膚問題有幫助。",
    whereToApply: "下背部、下腹部，以及整個軀幹。"
  }),

  createBottle(12, "新時代的和平", C.Clear, C.Blue, "光照亮和平，啟蒙與平靜的開始。", "光照亮了我的平靜。", ["Peace"], {
    alias: "Equilibrium_12 新時代的和平",
    mixedColor: "淡藍色",
    tarot: "倒吊人",
    positivePersonality: "一個和平、寧靜且富有慈悲心的人。能夠成為和平的管道。具有清晰的表達能力。",
    challengePersonality: "可能在權威議題上有困難。難以表達自己的需求，傾向於退縮或沈默。",
    spiritualLevel: "光照亮和平，帶來靈性的啟蒙與覺醒。幫助連結更高的意志。",
    mentalLevel: "帶來心智的清晰與平靜。",
    emotionalLevel: "釋放孤獨感與分離感。帶來被支持與被保護的感覺。",
    physicalLevel: "對喉嚨、甲狀腺、頸部與語言障礙有幫助。",
    whereToApply: "頸部與喉嚨周圍。"
  }),

  createBottle(13, "新時代的改變", C.Clear, C.Green, "在變動中找到方向，光照亮道路。", "我歡迎改變，改變帶來成長。", ["Change"], {
    alias: "Equilibrium_13 新時代的改變",
    mixedColor: "淡綠色",
    tarot: "死神",
    positivePersonality: "一個能夠適應改變、具有彈性且心胸開闊的人。在變動中能看到新的機會。與自然連結。",
    challengePersonality: "害怕改變，緊抓著過去不放。可能感到迷失方向或缺乏空間。",
    spiritualLevel: "光照亮道路，幫助在轉化過程中找到方向。釋放舊有的模式。",
    mentalLevel: "克服對未知的恐懼，做出明智的選擇。",
    emotionalLevel: "釋放情感上的束縛，帶來心的自由與空間。",
    physicalLevel: "對心臟、肺部與呼吸系統有益。幫助排毒。",
    whereToApply: "整個心輪區域（胸部）。"
  }),

  createBottle(14, "新時代的智慧", C.Clear, C.Gold, "清晰的智慧之光，釋放焦慮與恐懼。", "智慧是我的光，指引我前行。", ["Wisdom"], {
    alias: "Equilibrium_14 新時代的智慧",
    mixedColor: "淡金黃色",
    tarot: "節制",
    positivePersonality: "一個擁有內在智慧、自信且快樂的人。能夠將靈感落實為具體的行動。",
    challengePersonality: "可能深受深層恐懼或焦慮的困擾。缺乏自信，對未來感到茫然。",
    spiritualLevel: "光照亮內在的智慧，帶來清晰的覺知。幫助連結個人的力量。",
    mentalLevel: "消除混亂，帶來清晰的思考與專注力。",
    emotionalLevel: "釋放恐懼與緊張，帶來深層的喜悅與放鬆。",
    physicalLevel: "對太陽神經叢、消化系統、肝臟與腎臟有幫助。",
    whereToApply: "太陽神經叢周圍（肚臍上方）。"
  }),

  createBottle(15, "新時代的服務", C.Clear, C.Violet, "靈性的服務，將療癒帶入世界。", "我為了更高的善而服務。", ["Service"], {
    alias: "Equilibrium_15 新時代的服務",
    mixedColor: "淡紫色",
    tarot: "惡魔",
    positivePersonality: "一個具有高度靈性、致力於服務他人的人。擁有療癒的天賦與轉化的能力。",
    challengePersonality: "可能不想面對現實，或感到被犧牲。難以落實靈性的理想。",
    spiritualLevel: "光照亮靈性，帶來深層的轉化與療癒。提升服務的品質。",
    mentalLevel: "改變負面的思考模式，帶來正向的轉變。",
    emotionalLevel: "療癒深層的悲傷與失落。帶來內在的平靜與安詳。",
    physicalLevel: "對頭部、神經系統與失眠問題有幫助。",
    whereToApply: "沿著頭髮邊緣與頭頂。"
  }),

  createBottle(16, "紫袍", C.Violet, C.Violet, "靈性的覺醒與轉化，真正的服務。", "我臣服於更高的旨意，我即是服務。", ["Spirit"], {
    alias: "Equilibrium_16 紫袍",
    mixedColor: "紫色",
    tarot: "塔",
    positivePersonality: "一個完全奉獻於靈性道路的人。具有強大的轉化能力與治療力量。願意臣服於更高的旨意。",
    challengePersonality: "可能傾向於逃避現實，或陷入自憐自艾的情緒。難以處理憤怒。",
    spiritualLevel: "深層的靈性保護與淨化。幫助在變動中保持中心。",
    mentalLevel: "克服自我毀滅的念頭，轉化負面思維。",
    emotionalLevel: "釋放悲傷與憂鬱，帶來靈魂的慰藉。",
    physicalLevel: "對神經系統、頭痛、成癮問題有幫助。",
    whereToApply: "沿著頭髮邊緣與頭頂。"
  }),

  createBottle(17, "吟遊詩人 I / 希望", C.Green, C.Violet, "新的開始與希望，心的療癒。", "我心懷希望，相信未來。", ["Hope"], {
    alias: "Equilibrium_17 吟遊詩人 I",
    mixedColor: "深紫色",
    tarot: "星星",
    positivePersonality: "一個心胸寬大、具有遠見與創造力的人。在困難中仍能看到希望。致力於尋找真理。",
    challengePersonality: "可能感到絕望、被誤解或孤立。容易懷疑自己。",
    spiritualLevel: "帶來新的希望與靈感。連結心與靈性，找到真實的道路。",
    mentalLevel: "尋求真理，不再被外在表象迷惑。",
    emotionalLevel: "療癒心碎與情感創傷。釋放嫉妒與佔有欲。",
    physicalLevel: "對心臟、肺部與胸腺有益。",
    whereToApply: "整個胸部區域。"
  }),

  createBottle(18, "埃及瓶 I / 潮流的改變", C.Yellow, C.Violet, "釋放舊有模式，克服恐懼帶來的轉化。", "我釋放不再需要的，擁抱新生。", ["Change"], {
    alias: "Equilibrium_18 埃及瓶 I",
    mixedColor: "深金黃色",
    tarot: "月亮",
    positivePersonality: "一個在轉變中能保持智慧與覺知的人。能夠克服恐懼，轉化舊有的習氣。",
    challengePersonality: "可能被恐懼癱瘓，害怕面對未知。缺乏安全感。",
    spiritualLevel: "克服靈性上的自我欺騙。在黑暗中找到光。",
    mentalLevel: "區分幻象與真實。釋放限制性的信念。",
    emotionalLevel: "處理深層的焦慮與不安。帶來情感的轉化。",
    physicalLevel: "對消化系統與神經系統有幫助。",
    whereToApply: "太陽神經叢周圍。"
  }),

  createBottle(19, "生活在物質世界", C.Red, C.Violet, "將靈性光輝帶入物質生活。", "我在物質世界中活出靈性的光。", ["Energy"], {
    alias: "Equilibrium_19 生活在物質世界",
    mixedColor: "深紫紅色",
    tarot: "太陽",
    positivePersonality: "一個能量充沛、充滿魅力且具有靈性深度的人。能夠將靈性的洞見落實到日常生活中。",
    challengePersonality: "可能感到能量耗盡或被榨乾。在物質與靈性之間感到拉扯。",
    spiritualLevel: "靈性能量的電池。幫助在服務中恢復能量。",
    mentalLevel: "提升專注力與意志力。",
    emotionalLevel: "釋放憤怒與挫折感，轉化為創造性的力量。",
    physicalLevel: "對生殖系統、海底輪問題、能量低落有幫助。",
    whereToApply: "下腹部周圍。"
  }),

  createBottle(20, "星星小孩 / 兒童解救", C.Blue, C.Pink, "療癒內在小孩，無條件的愛與和平。", "我擁抱並療癒我的內在小孩。", ["Child"], {
    alias: "Equilibrium_20 星星小孩",
    mixedColor: "淡紫色",
    tarot: "審判",
    positivePersonality: "一個保有赤子之心、純真且充滿愛的人。能夠連結內在小孩的智慧。具有療癒能力。",
    challengePersonality: "可能感到受傷、缺乏愛或被遺棄。內在小孩需要療癒。",
    spiritualLevel: "連結靈魂原本的純淨與光。整合內在的男性與女性能量。",
    mentalLevel: "釋放批判，帶來自我接納。",
    emotionalLevel: "深層療癒童年創傷與情感缺憾。帶來溫柔的愛。",
    physicalLevel: "對懷孕、兒童疾病、長牙齒、發燒有幫助。",
    whereToApply: "身體的任何部位，特別是胸部與腹部。"
  }),

  createBottle(21, "愛的新開始", C.Green, C.Pink, "給予自己愛的新機會，原諒與釋放。", "我原諒自己，並展開愛的新旅程。", ["Love"]),
  createBottle(22, "重生者的瓶子 / 覺醒", C.Yellow, C.Pink, "無依賴的愛，在喜悅中覺醒。", "我在喜悅與愛中重生。", ["Joy"]),
  createBottle(23, "愛與光", C.RosePink, C.Pink, "找回對自己的愛，智慧與慈悲。", "我是愛，我是光，我是慈悲。", ["Love"]),
  createBottle(24, "新的訊息", C.Violet, C.Turquoise, "來自靈性的新洞見，心的溝通。", "我聆聽內在的聲音，傳遞新的訊息。", ["Message"]),
  createBottle(25, "恢復期 / 南丁格爾", C.Purple, C.Magenta, "釋放失望，從深處獲得療癒與滋養。", "我釋放失望，擁抱希望與療癒。", ["Healer"]),
  createBottle(26, "驚嚇瓶 / 乙太解救", C.Orange, C.Orange, "療癒生命中的驚嚇，整合碎片。", "唯一不變的就是改變，我安住在中心。", ["Rescue", "Shock"]),
  createBottle(27, "羅賓漢", C.Red, C.Green, "在熱情與冷靜間找到平衡，果斷行動。", "我找到內在的平衡點，並勇敢行動。", ["Balance"]),
  createBottle(28, "瑪麗安少女", C.Green, C.Red, "新的開始，充滿力量的覺醒。", "我準備好重新出發，展現真實力量。", ["Awakening"]),
  createBottle(29, "起身去做", C.Red, C.Blue, "將理想顯化為行動，帶來和平。", "我起而行，將夢想化為現實。", ["Action"]),
  createBottle(30, "把天堂帶到人間", C.Blue, C.Red, "將天堂品質帶入大地，溝通與能量。", "我在大地之上創造天堂。", ["Manifestation"]),
  createBottle(31, "泉源", C.Green, C.Gold, "克服深層恐懼，連結內在智慧之泉。", "我釋放恐懼，連結內在的智慧。", ["Fear"]),
  createBottle(32, "蘇菲亞", C.RoyalBlue, C.Gold, "來自上天的智慧，清晰的直覺。", "我跟隨內在之星的指引。", ["Wisdom"]),
  createBottle(33, "海豚瓶", C.RoyalBlue, C.Turquoise, "和平的溝通，透過遊戲表達創造力。", "我在和平與喜悅中遊戲。", ["Peace"]),
  createBottle(34, "金星的誕生", C.Pink, C.Turquoise, "愛與美的結合，展現創造性的愛。", "我在美中看見愛，在愛中看見美。", ["Love"]),
  createBottle(35, "仁慈", C.Pink, C.Violet, "無條件的愛與服務，溫柔的療癒。", "我以仁慈與愛對待一切。", ["Service"]),
  createBottle(36, "慈善", C.Violet, C.Pink, "慈悲的愛，接納自己與他人的本質。", "我慈悲地愛，不求回報。", ["Compassion"]),
  createBottle(37, "守護天使", C.Violet, C.Blue, "守護與滋養，帶來深層的平靜。", "我被守護著，我是安全的。", ["Angel"]),
  createBottle(38, "吟遊詩人 II / 辨識力", C.Violet, C.Green, "從心溝通，辨識真理與轉化。", "我說出我的真理，我走我的路。", ["Heart"]),
  createBottle(39, "埃及瓶 II / 演布袋戲的人", C.Violet, C.Gold, "古老的智慧，轉化與解放。", "我在改變中發現更深的智慧。", ["Wisdom"]),
  createBottle(40, "我是", C.Red, C.Gold, "自我覺知與行動，原始的智慧。", "我是，我存在。", ["Self"]),
  createBottle(41, "智慧瓶", C.Gold, C.Gold, "整合知識成為智慧，自我實現。", "我消化並整合我的經驗，成為智慧。", ["Wisdom"]),
  createBottle(42, "收成", C.Yellow, C.Yellow, "喜悅與慶祝，智慧的豐收。", "我歡慶生命中的豐盛與收穫。", ["Joy"]),
  createBottle(43, "創造力", C.Turquoise, C.Turquoise, "透過心來溝通，獨特的創造力。", "我是創造力的源頭，我自由表達。", ["Creativity"]),
  createBottle(44, "守護者", C.PaleViolet, C.PaleBlue, "轉化與保護，溫柔的平靜。", "我守護我的光，我被神性支持。", ["Protection"]),
  createBottle(45, "愛的氣息", C.Turquoise, C.Violet, "愛的呼吸，隨著生命之流給予與接受。", "我吸入愛，呼出愛。", ["Love"]),
  createBottle(46, "漂泊者", C.Green, C.Magenta, "在旅程中尋找真理與愛。", "真理在我心中，愛指引方向。", ["Search"]),
  createBottle(47, "古老的靈魂", C.RoyalBlue, C.LemonChiffon, "連結古老智慧，清晰的理性與直覺。", "我連結內在古老的智慧。", ["Soul"]),
  createBottle(48, "療癒的雙翅", C.Violet, C.Clear, "深層的淨化與療癒，看見光。", "我已痊癒，我展翅高飛。", ["Healing"]),
  createBottle(49, "新的信差", C.Turquoise, C.Violet, "表達深層感受，內在溝通的新層次。", "我真實地表達內在的聲音。", ["Message"]),
  createBottle(50, "艾爾摩雅", C.PaleBlue, C.PaleBlue, "祢的旨意，不是我的旨意。", "我讓更高的旨意流經我。", ["Master"]),
  createBottle(51, "庫圖米", C.PaleYellow, C.PaleYellow, "雙向溝通，與天使及眾生連結。", "我站在世界與世界之間，傳遞智慧。", ["Master"]),
  createBottle(52, "娜達女士", C.PalePink, C.PalePink, "無條件的愛，深層的自我接納。", "我完全地接納並愛著自己。", ["Master", "Love"]),
  createBottle(53, "希拉里昂", C.PaleGreen, C.PaleGreen, "道路、真理、生命，心的方向。", "我找到屬於我的道路與真理。", ["Master"]),
  createBottle(54, "瑟拉比斯貝", C.Clear, C.Clear, "光的淨化，理解痛苦背後的光。", "我看見事物背後的清晰與光。", ["Master"]),
  createBottle(55, "基督", C.Clear, C.Red, "犧牲的愛與能量的覺醒。", "光與能量在我之內合一。", ["Master"]),
  createBottle(56, "聖傑曼", C.PaleViolet, C.PaleViolet, "負面能量的轉化與釋放。", "我將一切轉化為光與愛。", ["Master"]),
  createBottle(57, "雅典娜與伊奧拉斯", C.PalePink, C.PaleBlue, "創造力與正確的生計，放手與信任。", "我信任生命，放手讓一切發生。", ["Master"]),
  createBottle(58, "奧利安與安洁莉卡", C.PaleBlue, C.PalePink, "內在與外在的旅程，開始與結束。", "我在當下，擁抱旅程的每一步。", ["Master"]),
  createBottle(59, "波夏女士", C.PaleYellow, C.PalePink, "正義與辨識力，以愛停止批判。", "我以愛與慈悲來衡量一切。", ["Master"]),
  createBottle(60, "老子與觀音", C.Blue, C.Clear, "極致的寧靜與平靜，順流而行。", "我如水般柔軟而充滿力量。", ["Master"]),
  createBottle(61, "薩納特庫瑪拉與維纳斯庫瑪拉", C.PalePink, C.PaleYellow, "神聖的愛，看穿幻象見真理。", "我在深層看見神聖的愛。", ["Master"]),
  createBottle(62, "瑪哈霍汗", C.PaleTurquoise, C.PaleTurquoise, "內在導師的聲音，心的連結。", "我聆聽內在導師的指引。", ["Master"]),
  createBottle(63, "迪瓦庫與希拉里昂", C.EmeraldGreen, C.PaleGreen, "新開始的真理，空間與方向。", "我理解並活出我的真理。", ["Master"]),
  createBottle(64, "迪瓦庫", C.EmeraldGreen, C.Clear, "尋求真理的空間，唯有真理使人自由。", "真理是我唯一的道路。", ["Master"]),
  createBottle(65, "頭在天，腳在地", C.Violet, C.Red, "落實靈性，將天堂帶入大地。", "我連結天地，活在當下。", ["Balance"]),
  createBottle(66, "女演員", C.PaleViolet, C.PalePink, "在角色中看見真實，無條件的服務。", "我超脫角色，看見真實的自己。", ["Role"]),
  createBottle(67, "小事中的愛", C.Magenta, C.Magenta, "在微小事物中看見神聖的愛。", "愛存在於每一個細節之中。", ["Love"]),
  createBottle(68, "加百列", C.Blue, C.Violet, "和平與靈性，天使的訊息與溝通。", "我傳遞和平與靈性的訊息。", ["Angel"]),
  createBottle(69, "響亮的鐘聲", C.Magenta, C.Clear, "熱情的愛，淨化與釋放。", "愛是我靈魂的聲音。", ["Love"]),
  createBottle(70, "燦爛的景象", C.Yellow, C.Clear, "清晰的異象，光照亮智慧。", "我看見生命的輝煌與光。", ["Vision"]),
  createBottle(71, "蓮花中的寶石", C.Pink, C.Clear, "發現內在的寶藏，無條件的愛。", "我發現內在珍貴的寶石。", ["Self"]),
  createBottle(72, "小丑", C.Blue, C.Orange, "轉化悲傷，接納內在的小丑。", "我接納並表達真實的情緒。", ["Emotion"]),
  createBottle(73, "莊子", C.Gold, C.Clear, "深層的智慧與轉化，內在的煉金術。", "智慧來自內在的寧靜。", ["Wisdom"]),
  createBottle(74, "勝利", C.PaleYellow, C.PaleGreen, "戰勝考驗後的清晰與喜悅。", "我戰勝挑戰，迎來光明。", ["Triumph"]),
  createBottle(75, "順流而行", C.Magenta, C.Turquoise, "跟隨生命的流動，愛與創造力。", "我順流而行，不逆流而上。", ["Flow"]),
  createBottle(76, "信任", C.Pink, C.Gold, "透過愛與智慧建立信任。", "我信任愛，我信任自己。", ["Trust"]),
  createBottle(77, "杯子", C.Clear, C.Magenta, "成為光的載體，神聖的愛之容器。", "我是光與愛的純淨容器。", ["Light"]),
  createBottle(78, "頂輪救援", C.Violet, C.DeepMagenta, "深層靈性轉化，連結源頭。", "我與宇宙源頭合而為一。", ["Rescue"]),
  createBottle(79, "鴕鳥瓶", C.Orange, C.Violet, "面對挑戰的洞見，不再逃避。", "我勇敢面對生命中的挑戰。", ["Challenge"]),
  createBottle(80, "阿耳忒彌斯", C.Red, C.Pink, "愛的力量，喚醒沉睡的能量。", "愛是我行動的力量。", ["Energy"]),
  createBottle(81, "無條件的愛", C.Pink, C.Pink, "自我接納，無條件的愛。", "我就是愛，我無條件地愛自己。", ["Love"]),
  createBottle(82, "卡呂普索", C.Green, C.Orange, "釋放深層情緒，獲得洞見與歡慶。", "我釋放過去，在喜悅中起舞。", ["Emotion"]),
  createBottle(83, "芝麻開門", C.Turquoise, C.Gold, "打開古老智慧的門戶，個體化。", "我打開內在的智慧寶庫。", ["Wisdom"]),
  createBottle(84, "風中之燭", C.Pink, C.Red, "燃燒熱情與愛，覺醒的力量。", "我讓愛的火焰在心中燃燒。", ["Passion"]),
  createBottle(85, "泰坦尼亞", C.Turquoise, C.Clear, "精靈女王，透過感受表達創造力。", "我真實地表達我的創造力。", ["Creativity"]),
  createBottle(86, "奧伯龍", C.Clear, C.Turquoise, "精靈王，清晰地與心溝通。", "我清晰地創造我想要的生活。", ["Creativity"]),
  createBottle(87, "愛的智慧", C.PaleCoral, C.PaleCoral, "療癒單戀與無回報的愛，獲得智慧。", "我以智慧與慈悲看待愛。", ["Archangel", "Love"]),
  createBottle(88, "玉皇大帝", C.Green, C.Blue, "與自然連結，深層的和平。", "我與大自然和諧共存。", ["Nature"]),
  createBottle(89, "能量解救", C.Red, C.DeepMagenta, "時間軸的療癒，重獲能量。", "我在此時此刻，重獲新生。", ["Rescue"]),
  createBottle(90, "智慧解救", C.Gold, C.DeepMagenta, "釋放深層恐懼，轉化為智慧。", "智慧治癒了我內在的恐懼。", ["Rescue"]),
  createBottle(91, "女性領導力", C.Olive, C.Olive, "心的領導，信任直覺與女性面。", "我以心與直覺來領導。", ["Leadership"]),
  createBottle(92, "葛麗特", C.PaleCoral, C.Olive, "信任直覺，療癒女性面向的依賴。", "我信任我的直覺，我獨立而完整。", ["Intuition"]),
  createBottle(93, "韓賽爾", C.PaleCoral, C.Turquoise, "集體意識的溝通，療癒男性面向。", "我向宇宙智慧敞開，自在溝通。", ["Communication"]),
  createBottle(94, "大天使麥可", C.PaleYellow, C.PaleBlue, "信任神聖意志，釋放恐懼。", "我放下恐懼，信任更高的安排。", ["Archangel"]),
  createBottle(95, "大天使加百列", C.Magenta, C.Gold, "靈魂的信差，結合愛與智慧。", "我接收並傳遞靈魂的訊息。", ["Archangel"]),
  createBottle(96, "大天使拉斐爾", C.RoyalBlue, C.RoyalBlue, "高等心靈與直覺，深層的平靜。", "我透過感官與直覺看見神性。", ["Archangel"]),
  createBottle(97, "大天使烏列爾", C.Gold, C.RoyalBlue, "內在的太陽，將光帶入世界。", "我的光照亮自己，也照亮世界。", ["Archangel"]),
  createBottle(98, "大天使桑德芬", C.Lilac, C.PaleCoral, "轉化負面能量，地上的天使。", "我轉化挑戰，帶來和諧與合作。", ["Archangel"]),
  createBottle(99, "大天使薩基爾", C.PaleOlive, C.Pink, "新的開始，釋放不再需要的。", "我擁抱宇宙之愛，展開新生。", ["Archangel"]),
  createBottle(100, "大天使梅塔特隆", C.Clear, C.DeepMagenta, "光與影的整合，照見內在深處。", "我接納光與影，看見完整的自己。", ["Archangel"]),
  createBottle(101, "大天使約菲爾", C.PaleBlue, C.PaleOlive, "心的放鬆與回歸，信任過程。", "我的心是自由的，我信任生命。", ["Archangel"]),
  createBottle(102, "大天使薩麥爾", C.DeepOlive, C.DeepMagenta, "深層的保護，在困境中看見希望。", "我在希望中，平安與我同在。", ["Archangel"]),
  createBottle(103, "大天使漢尼爾", C.OpalescentTurquoise || C.PaleBlue, C.DeepMagenta, "月亮的能量，光輝與保護。", "我在月光下安息，閃耀光芒。", ["Archangel"]),
  createBottle(104, "大天使卡麥爾", C.RosePink, C.Magenta, "神聖的愛，原諒與接納。", "愛是存在的本質，我就是愛。", ["Archangel"]),
  createBottle(105, "大天使阿茲瑞爾", C.Coral, C.Coral, "超越分離與黑暗，合一的洞見。", "我們是一體的，愛永不分離。", ["Archangel"]),
  createBottle(106, "大天使拉結爾", C.PaleOlive, C.Lilac, "煉金術的轉化，業力的釋放。", "我轉化過去的經驗成為智慧。", ["Archangel"]),
  createBottle(107, "大天使薩普基爾", C.OpalescentTurquoise || C.Turquoise, C.DeepMagenta, "神聖母親的愛，海洋般的包容。", "我在愛的海洋中，被溫柔地承接。", ["Archangel"]),
  createBottle(108, "大天使耶利米爾", C.MidToneTurquoise, C.MidToneOlive, "審視過去，獲得清晰的洞見與希望。", "我清晰地看見過去，並對未來充滿希望。", ["Archangel"]),
  createBottle(109, "大天使薩迦利爾", C.Magenta, C.MidToneOlive, "愛與寬恕，帶來新的希望。", "我寬恕一切，勇敢前行。", ["Archangel"]),
  createBottle(110, "大天使安布瑞爾", C.PaleRosePink, C.DeepMagenta, "慈悲的愛與保護，釋放怨恨。", "愛保護著我，我選擇慈悲。", ["Archangel"]),
  createBottle(111, "大天使但以理", C.MidToneRoyalBlue, C.MidToneOlive, "分辨真理，恢復清晰的視野。", "我看見真理，我的視野清晰。", ["Archangel"]),
  createBottle(112, "大天使伊斯拉菲爾", C.Turquoise, C.MidToneRoyalBlue, "創造性的流動，透過心表達真實。", "我在流動中創造，表達真實的自己。", ["Archangel"]),
  createBottle(113, "大天使卡西爾", C.EmeraldGreen, C.MidToneOlive, "深層的轉化，找到新的方向。", "我擁抱轉化，走向新的方向。", ["Archangel"]),
  createBottle(114, "拉貴爾", C.MidToneCoral, C.DeepMagenta, "人際關係的和諧，朋友如同家人。", "我在關係中創造和諧與尊重。", ["Archangel"]),
  
  // B115 - Detailed Update
  createBottle(115, "凱米爾與艾瑞爾", C.Orange, C.Red, "擁抱內在女性面，展現真實的愛與勇氣。", "我榮耀內在的女神，並以勇氣活出愛的真諦。", ["Archangel"], {
    alias: "Equilibrium_115 115-凱米爾與艾瑞爾",
    mixedColor: "珊瑚色",
    tarot: "未知", 
    positivePersonality: "這是一個與「整合」有關的瓶子，特別是關於內在女性力量的整合。代表能夠深入自己的直覺與感受，並以充滿勇氣的行動將這份柔軟帶入世界。具有強大的轉化能力，能將對抗轉化為合作。",
    challengePersonality: "可能在權威議題上有困難，或難以協調內在的衝突。有時會因為過度保護自己而顯得具攻擊性，其實內心渴望深層的連結。",
    spiritualLevel: "幫助連結大地母親的能量，在物質世界中落實靈性的光。支持亢達里尼能量的升起，帶來深層的覺醒。",
    mentalLevel: "帶來清晰的決斷力，但這種決斷是基於愛而非恐懼。幫助釋放過時的信念系統。",
    emotionalLevel: "療癒與母親或女性面向的關係。釋放深層的羞愧或罪惡感，讓人能夠真實地表達情感。",
    physicalLevel: "對於下腹部、生殖系統的能量阻塞有助益。幫助恢復身體的活力與熱情。",
    whereToApply: "下腹部周圍，以及脊椎底部。"
  }),

  createBottle(116, "麥布女王", C.RoyalBlue, C.Magenta, "深層的平靜與直覺，夢境的指引。", "我信任我的直覺與夢境。", ["Royal"]),
  createBottle(117, "潘", C.Turquoise, C.Red, "自然與靈性，創造力的顯化。", "我在自然中顯化我的創造力。", ["Nature"]),
  createBottle(118, "回音", C.PaleCoral, C.PaleViolet, "聆聽內在的聲音，超越投射。", "我聆聽內在真實的聲音。", ["Myth"]),
  createBottle(119, "瑟雷斯", C.Orange, C.DeepMagenta, "療癒創傷，種下光的種子。", "我被大地滋養，充滿豐盛。", ["Goddess"]),
  createBottle(120, "泊瑟芬", C.Clear, C.Orange, "走出黑暗，在光中重生。", "我釋放過去，在光中重生。", ["Goddess"]),
  createBottle(121, "普魯托", C.LimeGreen, C.Orange, "深層的轉化，邁向新的時間軸。", "我轉化並前進，創造新的未來。", ["God"]),
  createBottle(122, "波塞頓", C.BrightMagenta, C.LimeGreen, "深層的情感釋放，愛的海洋。", "我在愛的海洋中，自由流動。", ["God"]),
  createBottle(123, "瑞亞", C.LemonYellow, C.RoyalBlue, "放手與信任，意識的甦醒。", "我放手信任，在流動中甦醒。", ["Goddess"]),
];

export const POSITIONS = [
  { id: 1, title: "靈魂瓶 (Soul)", desc: "你來到世上的使命與目的" },
  { id: 2, title: "天賦與挑戰 (Gifts & Challenges)", desc: "主要的困難與潛在的禮物" },
  { id: 3, title: "當下 (Here & Now)", desc: "你現在的狀態與能量" },
  { id: 4, title: "未來 (Future)", desc: "即將到來的能量走向" },
];